# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: The Impractical Engineer
email: fabianspublicemail@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  My name is Fabian Trauzettel. I'm a Biomedical engineer working in research, and this is where I post work, side projects and whatever else I feel like. You will never find a more wretched hive of scum and miscellany.
  
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://theimpractical.engineer" # the base hostname & protocol for your site, e.g. http://example.com
#twitter_username:
github_username:  FabianTz

# Build settings
markdown: kramdown
theme: minima
gems:
  - jekyll-feed
exclude:
  - Gemfile
  - Gemfile.lock
